//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Cat.
    /// </summary>
    //  *** Start programmer edit section *** (Cat CustomAttributes)

    //  *** End programmer edit section *** (Cat CustomAttributes)
    [AutoAltered()]
    [Caption("Кот")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CatE", new string[] {
            "Name as \'Name\'",
            "Age"})]
    [View("CatL", new string[] {
            "Name as \'Name\'",
            "Age"})]
    public class Cat : ICSSoft.STORMNET.DataObject
    {
        
        private int fAge;
        
        private string fName;
        
        //  *** Start programmer edit section *** (Cat CustomMembers)

        //  *** End programmer edit section *** (Cat CustomMembers)

        
        /// <summary>
        /// Age.
        /// </summary>
        //  *** Start programmer edit section *** (Cat.Age CustomAttributes)

        //  *** End programmer edit section *** (Cat.Age CustomAttributes)
        public virtual int Age
        {
            get
            {
                //  *** Start programmer edit section *** (Cat.Age Get start)

                //  *** End programmer edit section *** (Cat.Age Get start)
                int result = this.fAge;
                //  *** Start programmer edit section *** (Cat.Age Get end)

                //  *** End programmer edit section *** (Cat.Age Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Cat.Age Set start)

                //  *** End programmer edit section *** (Cat.Age Set start)
                this.fAge = value;
                //  *** Start programmer edit section *** (Cat.Age Set end)

                //  *** End programmer edit section *** (Cat.Age Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Cat.Name CustomAttributes)

        //  *** End programmer edit section *** (Cat.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Cat.Name Get start)

                //  *** End programmer edit section *** (Cat.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Cat.Name Get end)

                //  *** End programmer edit section *** (Cat.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Cat.Name Set start)

                //  *** End programmer edit section *** (Cat.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Cat.Name Set end)

                //  *** End programmer edit section *** (Cat.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CatE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CatE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatE", typeof(IIS.Test.Cat));
                }
            }
            
            /// <summary>
            /// "CatL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CatL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatL", typeof(IIS.Test.Cat));
                }
            }
        }
    }
}
